apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name | default .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name | default .Release.Name }}
spec:
  claimRef:
    name: {{ .Values.name | default .Release.Name }}
    namespace: {{ .Values.namespace | default .Release.Namespace }}
  accessModes:
    - {{ .Values.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.reclaimPolicy }}
  capacity:
    storage: {{ .Values.storage | quote }}
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: {{ .Values.name | default .Release.Name }}
    volumeAttributes:
      server: {{ .Values.server | quote }}
      share: {{ if .Values.shareFullPath }}{{ .Values.shareFullPath }}{{ else }}{{ .Values.share }}/{{ .Values.name | default .Release.Name }}{{ end }}
  storageClassName: ""
