apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.name }}"
  namespace: "{{ .Values.namespace }}"
spec:
  accessModes:
    - {{ .Values.accessMode }}
  resources:
    requests:
      storage: "{{ .Values.storage }}"
  storageClassName: ""
