name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ github.repository }}

      - name: Workaround
        run: git init

      - name: Helm Publisher
        uses: stefanprodan/helm-gh-pages@v1.5.0
        with:
          charts_dir: ${{ github.repository_owner }}
          token: ${{ github.token }}
