name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release Chart
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: .
        env:
          CR_TOKEN: ${{ github.token }}
